### ISSUE TITLE
kextract file couldn't be generated (kernel commit: mainline 012e3ca3cb4d7f, kmax: v4.3.1, arch: arm64)

### ISSUE THREAD

**Issue by Yujie-Liu** [paulgazz/kmax#164]
```
$ kmax --version
kmax 4.3.1

$ cd linux
$ git checkout 012e3ca3cb4d7f
HEAD is now at 012e3ca3cb4d media: platform: rename omap/ to ti/omap/

$ ls arch/ | grep arm
arm
arm64   <-- arm64 arch is there

$ kismet -a arm64
INFO: Computing the build system id for the Linux source..
INFO: Build system id: f5811de66f61
INFO: Kismet will analyze the select constructs of the architecture "arm64" for unmet direct dependency.
INFO: All times reported are measured using Python's time.perf_counter() utility.
INFO: Prefetching the architecture kclause formulas.
ERROR:Arch(arm64): Error running kextract: kextract file couldn't be generated.
Traceback (most recent call last):
  File "/env_kmax/bin/kismet", line 411, in <module>
    if sample_models: arch.get_kextract() # for sampling
  File "/env_kmax/lib/python3.9/site-packages/kmax/arch.py", line 579, in get_kextract
    self.__ensure_formulas(self.__kextract, self.__kextract_file_delayed_load, self.load_kextract, self.generate_kextract)
  File "/env_kmax/lib/python3.9/site-packages/kmax/arch.py", line 494, in __ensure_formulas
    formula_generation_method()
  File "/env_kmax/lib/python3.9/site-packages/kmax/arch.py", line 782, in generate_kextract
    raise Arch.KextractFormulaGenerationError()
kmax.arch.Arch.KextractFormulaGenerationError: kextract formulas couldn't be generated.
```

**Comment by paulgazz** [comment]
When I try to process the Kconfig specs manually with kextractlinux arm64 kextract_arm64.out I get the following error:

    drivers/media/platform/Kconfig:69: can't open file "drivers/media/platform/am437x/Kconfig"

This file is indeed missing and if I touch it, kextract and kismet then work.  It looks like our Kconfig processor is halting if there are missing Kconfig files.  I think the resolution would be to (perhaps optionally) treat such issues as warnings rather than errors and continue to try processing the Kconfig files.

**Comment by Yujie-Liu** [comment]
Hi, @paulgazz, thanks for the analysis. Since it is caused by a missing file, does it mean that it is a kernel code bug that the author forgot to add Kconfig file for that device driver? It would be nice to treat such issues as warnings to keep kismet running, but would this issue show up in the result? such as a warning in summary.txt, an entry in summary.csv or simply a warning log to stdout/stderr? thanks.

**Comment by paulgazz** [comment]
I suppose this would be a bug, though I will reconfirm that this is the case.  Since Kconfig didn't seem to report it when I tried running `make defconfig`, I think we can just attempt to validate kismet's bug the same way (by making a .config file) and only report an issue if Kconfig itself actually produces an error.  I think this would require updating how we detect errors though.  @necipfazil can you comment on whether this would be something in summary.csv or just in our stderr/stdout?

**Comment by necipfazil** [comment]
@paulgazz `make defconfig` seem to complain about the missing Kconfig file for me:

```
$ make defconfig
*** Default configuration is based on 'x86_64_defconfig'
drivers/media/platform/Kconfig:69: can't open file "drivers/media/platform/am437x/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:87: defconfig] Error 1
make: *** [Makefile:619: defconfig] Error 2
```
```
$ make ARCH=arm64 defconfig
*** Default configuration is based on 'defconfig'
drivers/media/platform/Kconfig:69: can't open file "drivers/media/platform/am437x/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:87: defconfig] Error 1
make: *** [Makefile:619: defconfig] Error 2
```

running `make olddefconfig` on some .config (allnoconfig for another version) also complains about the missing Kconfig file:
```
$ make olddefconfig
drivers/media/platform/Kconfig:69: can't open file "drivers/media/platform/am437x/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:77: olddefconfig] Error 1
make: *** [Makefile:619: olddefconfig] Error 2
```

This seems to be the up-to-date behavior of Kconfig as I see the same error when I try deleting a Kconfig file and running `make defconfig` on a recent Linux kernel version.

We can have `kismet` proceed with a warning but this can lead to false positives/negatives as there will be missing configuration option definitions from the missing Kconfig file. In such case, the warning would appear in stderr/stdout of `kismet` since this issue belongs to the whole Kconfig specifications analyzed, rather than specific configuration options.

Alternatively, `kismet` can terminate with an error message on stderr/stdout without continuing the analysis because it does not have a complete Kconfig specifications to analyze.

@paulgazz what do you think?

**Comment by paulgazz** [comment]
Thanks, @necipfazil I must’ve remembered wrong about defconfig.  I thought I had run at least some config…  If indeed Kconfig also considers this an error, then I think it doesn’t make sense to have kismet proceed, since the .config may not be buildable anyway due to this error.  I guess just reporting this as an error on stder/stdout seems to make sense, but I don’t have any particular preference.  @Yujie-Liu does this work for you?

**Comment by Yujie-Liu** [comment]
@paulgazz yes, it's nice to print an error to stderr and stop kismet. By the way, I noticed that the INFO log showing the running status of kismet is printed to stderr by default. It would be better to print normal log to stdout, and print warning/error log to stderr, so we can easily redirect the output stream to catch the error.

**Comment by necipfazil** [comment]
@Yujie-Liu @paulgazz https://github.com/paulgazz/kmax/pull/169 prints a specific error in such cases and stops kismet. After this gets merged, the error can be caught by grep'ing for the following message in the stderr of kismet: `ERROR: Can't open Kconfig files:`

**Comment by necipfazil** [comment]
@Yujie-Liu thanks for the suggestion on streaming info messages on stdout. I believe we used to use stdout for a different output from `kismet` but that does not seem to be the case anymore. @paulgazz https://github.com/paulgazz/kmax/pull/170 moves info logs to stdout.
